In [2]:
import pandas as pd

In [3]:
df= pd.read_csv('publications.csv',index_col=0)

In [12]:
df

,page,page_text,has_akkadian
pdf_name,,,
"(OCR) AfO 51, 2005-06, pp. 247-249 - Kryszat, Guido - Altassyrische Miszellen 2 - Zur Gottin Istar - ZA.AT.pdf",1,Kleine Mitteilungen\nAltassyrische Miszellen 2...,False
"(OCR) AfO 51, 2005-06, pp. 247-249 - Kryszat, Guido - Altassyrische Miszellen 2 - Zur Gottin Istar - ZA.AT.pdf",2,248\nKleine Mitteilungen\nKleine Mitteilungen\...,False
"(OCR) AfO 51, 2005-06, pp. 247-249 - Kryszat, Guido - Altassyrische Miszellen 2 - Zur Gottin Istar - ZA.AT.pdf",1,Kleine Mitteilungen\nAltassyrische Miszellen 2...,False
"(OCR) AfO 51, 2005-06, pp. 247-249 - Kryszat, Guido - Altassyrische Miszellen 2 - Zur Gottin Istar - ZA.AT.pdf",2,248\nKleine Mitteilungen\nKleine Mitteilungen\...,False
"(OCR) CDOG 8, 2008, pp. 109-124 - Dercksen, J.G. - The Assyrian Colony at Kanesh.PDF",1,THE AssYRIAN COLONY AT KANEsH\nJan Gerrit Derc...,False
...,...,...,...
"AKT 2, 1995.pdf",76,"60\nANKARA KÜLTEPE TABLETLERİ II\nNo. 31, imat...",True
"AKT 2, 1995.pdf",77,ANKARA KÜLTEPE TABLETLERİ II\n(>1\nK.\na-ha-at...,False
"AKT 2, 1995.pdf",78,62\nANKARA KÜLTEPE TABLETLERİ II\n30: tudittum...,False
"AKT 2, 1995.pdf",79,ANKARA KÜLTEPE TABLETLERİ II\n63\nK.\nlu is-ti...,True
"AKT 2, 1995.pdf",80,64\nANKARA KÜLTEPE TABLETLERİ II\n9: satırdaki...,False

In [11]:
df['pdf_name'][df['pdf_name']=='AKT 2, 1995.pdf']

KeyError: 'pdf_name'

In [9]:
df.iloc[76,1]

'İÇİNDEKİLER\\nFethi Ahmet YÜKSEL, Osman AYTEKİN\\nArtvin-Şavşat Kalesi 2009 Dönemi Arkeojeoﬁzik Araştırmaları ............................1\\nFethi Ahmet YÜKSEL, Emine DÖNMEZ\\nAmasya (Harşena) Kalesi 2009 Arkeojeoﬁzik Araştırmaları ..................................13\\nAyşe Ç. TÜRKER\\nByzantine Architectural Sculpture and Liturgical Stonework in Çanakkale\\nArcheology Museum-Studies in 2009 ..................................................................27\\nTayfun YILDIRIM, Tunç SİPAHİ\\n2009 Yılı Çankırı Çorum Yüzey Araştırması ..........................................................39\\nChristopher H. ROOSEVELT\\nCentral Lydia Archaeological Survey, 2009 Results ................................................55\\nLutgarde VANDEPUT, Veli KÖSE, Mark JACKSON\\nPisidia Survey Project 2009:Research in the Territory of Pednelissos ....................75\\nS. MAZZONI, A. D’AGOSTINO, V. ORSI\\nUşaklı/Kuşaklı Höyük(Yozgat-Sorgun):the 2009 Survey(University of Florence) ..91\\nAsnu BİLBAN YALÇIN\\nBoğaziçi Topografyası: 2009 Araştırmaları ............................................................105\\nSuat ATEŞLİER\\nEuromos Arkaik Mimarî Terracottaları (Arkaik Tapınak Üzerine Düşünceler) .....123\\nH. VANHAVERBEKE, M. WAELKENS, I. JACOBS, M. LEFERE,\\nE. KAPTIJN, J. POBLOME\\nThe 2008 and 2009 Survey Season in the Territory of Sagalassos ........................139\\nMaria ANDALORO\\nThe Project on the Rock Paintings in Cappadocia and the Church of the Forty\\nMartyrs in Şahinefendi. Analyses and Restoration (Report 2009) .......................155\\nA. Osman UYSAL\\nÇanakkale İli Ortaçağ ve Türk Dönemi Yüzey Araştırması\\n2009 Yılı Çalışmaları ..............................................................................................173\\nAdnan DİLER, B.ÖZER, Ş. GÜMÜŞ, H.Ö. ÖZCAN, M.ELMAS, A.NOVALİÇ\\nBodrum Yarımadası Leleg yerleşimleri, Adalar, Aspat, Kissebükü (Anastasioupolis),\\nMylasa Damlıboğaz (Hydai), Pilavtepe ve Sedir Adası Yüzey Araştırmaları-\\n2009..........................................................................................................................187\\nPeter RUGGENDORFER\\nUntersuchungen zur städtebaulichen Entwicklung und\\nzur Geschichte von Alinda 2009 .............................................................................207\\nMartin BACHMANN\\n2009 Yılı Oinoanda Çalışmaları ..............................................................................221'

LOWERCASING

In [197]:
df

,transliteration,translation
oare_id,,
004a7dbd-57ce-46f8-9691-409be61c676e,kišib ma-nu-ba-lúm-a-šur dumu ṣí-lá-(d)im kiši...,"seal of mannum-balum-aššur son of ṣilli-adad, ..."
0064939c-59b9-4448-a63d-34612af0a1b5,1 túg ša qá-tim i-tur₄-dingir il₅-qé,itūr-ilī has received one textile of ordinary ...
0073f2c0-524c-4bbf-915a-8c1772a4fb98,túg u-la i-dí-na-ku-um i-tù-ra-ma 9 gín kù.babbar,... he did not give you a textile. he returned...
009fb838-8038-42bc-ad34-5f795b3840ee,kišib šu-(d)en.líl dumu šu-ku-bi-im kišib ṣí-l...,"seal of šu-illil son of šu-kūbum, seal of ṣilū..."
00aa1c55-c80c-4346-a159-73ad43ab0ff7,um-ma šu-ku-tum-ma a-na ištar-lá-ma-sí ù ni-ta...,from šukkutum to ištar-lamassī and nitahšušar:...
...,...,...
ff3208e4-8ab8-4368-b4df-7b80afa5bc32,um-ma en-nam-a-šur-ma a-na a-la-ḫi-im qí-bi-ma...,from ennam-aššur to ali-ahum: here 2 men have ...
ff43a284-3d67-4238-8b4a-9b6cb7531e0a,3 ma-na kù.babbar ṣa-ru-pá-am i-na ší-im síg.ḫ...,ilī-ašrannī son of sukkalliya has received 3 m...
ff5747a4-af8a-4100-a906-a2660ae72606,ša-lim-a-šùr a-na a-mur-ištar ú-ṭá-ḫi-ni-a-tí-...,šalim-aššur made us approach amur-ištar and ša...
ff777871-97ce-4bfc-bdfb-73352868944d,a-na en-nam-a-šùr qí-bi-ma um-ma ištar-ra-bi₄-...,to ennam-aššur from ištar-rabiʾat: with respec...
ff9442fd-9e7d-449c-a2d6-0cc35921cd65,um-ma ša ki-ma a-šùr-i-mì-tí dumu i-ku-pí-išta...,the representatives of aššur-imittī son of ikū...

In [196]:
df['transliteration']= df['transliteration'].str.lower()
df['translation']= df['translation'].str.lower()

TAGS/REGEX

Remove (modern scribal notations): ! (certain reading) ? (questionable reading) / (line divider) : OR . (word divider) < > (scribal insertions, but keep the text in translit / translations) ˹ ˺ (partially broken signs, to be removed from transliteration) [ ] (remove from document level transliteration. e.g. [KÙ.BABBAR] → KÙ.BABBAR)

In [6]:
import re
def clean_scribal_notations(text):
    if pd.isna(text):
        return text

    text = re.sub(r'<([^>]*)>', r'\1', text)
    text = re.sub(r'\[([^\]]*)\]', r'\1', text)
    text = re.sub(r'[!?/:.\u02F9\u02FA]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [15]:
df['transliteration'] =df['transliteration'].apply(join_hyphenated_symbols)

In [16]:
df['translation'] =df['translation'].apply(join_hyphenated_symbols)

In [10]:
import re
import pandas as pd

SUBSCRIPT_MAP = str.maketrans(
    "₀₁₂₃₄₅₆₇₈₉",
    "0123456789"
)

def normalize_transliteration(text):
    if pd.isna(text):
        return text

    # 1. Explicit gaps
    text = re.sub(r'\[x\]', '<gap>', text)

    # 2. Big gaps
    text = re.sub(r'\[\s*…\s*…\s*\]', '<big_gap>', text)
    text = re.sub(r'…', '<big_gap>', text)

    # 3. Remove gloss braces
    text = re.sub(r'\b(\w+)\s*\{\1\}', r'\1', text)

    
    # 4. Normalize subscripts
    text = text.translate(SUBSCRIPT_MAP)

    # 5. Remove broken-sign markers
    text = re.sub(r'[\u02F9\u02FA]', '', text)

    # 6. Normalize modifier apostrophe
    text = re.sub(r'\u02BE', "'", text)

    # 7. Remove editorial symbols
    text = re.sub(r'[!?/:.]', '', text)

    # 8. Normalize whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [14]:
import re
import pandas as pd

def join_hyphenated_symbols(text):
    if pd.isna(text):
        return text

    # Join tokens split by hyphens
    # ma-nu-ba-lúm-a-šur → manubalúmašur
    # ṣí-lá-(d)IM → ṣílá(d)IM
    text = re.sub(r'(?<=\S)-(?=\S)', '', text)

    return text

In [17]:
df

,transliteration,translation
oare_id,,
004a7dbd-57ce-46f8-9691-409be61c676e,KIŠIB manubalúmašur DUMU ṣílá(d)IM KIŠIB šu(d)...,"Seal of MannumbalumAššur son of ṢilliAdad, sea..."
0064939c-59b9-4448-a63d-34612af0a1b5,1 TÚG ša qátim itur4DINGIR il5qé,Itūrilī has received one textile of ordinary q...
0073f2c0-524c-4bbf-915a-8c1772a4fb98,TÚG ula idínakuum itùrama 9 GÍN KÙBABBAR,he did not give you a textile He returned and ...
009fb838-8038-42bc-ad34-5f795b3840ee,KIŠIB šu(d)ENLÍL DUMU šukubiim KIŠIB ṣílulu DU...,"Seal of ŠuIllil son of ŠuKūbum, seal of Ṣilūlu..."
00aa1c55-c80c-4346-a159-73ad43ab0ff7,umma šukutumma ana IŠTARlámasí ù nitaaḫšušar q...,From Šukkutum to Ištarlamassī and Nitahšušar W...
...,...,...
ff3208e4-8ab8-4368-b4df-7b80afa5bc32,umma ennamašurma ana alaḫiim qíbima anakam adu...,From EnnamAššur to Aliahum Here 2 men have rea...
ff43a284-3d67-4238-8b4a-9b6cb7531e0a,3 mana KÙBABBAR ṣarupáam ina šíim SÍGḪIA ša úš...,Ilīašrannī son of Sukkalliya has received 3 mi...
ff5747a4-af8a-4100-a906-a2660ae72606,šalimašùr ana amurIŠTAR úṭáḫiniatíma umma šali...,ŠalimAššur made us approach AmurIštar and Šali...
ff777871-97ce-4bfc-bdfb-73352868944d,ana ennamašùr qíbima umma IŠTARrabi4atma adí K...,To EnnamAššur from Ištarrabi'at With respect t...
ff9442fd-9e7d-449c-a2d6-0cc35921cd65,umma ša kima ašùrimìtí DUMU ikupíIŠTARma ašùri...,The representatives of Aššurimittī son of Ikūn...

In [18]:
import re
import pandas as pd

ATF_ASCII_TO_UNICODE = {
    r'sz': 'š',
    r'SZ': 'Š',

    r's,': 'ṣ',
    r'S,': 'Ṣ',

    r't,': 'ṭ',
    r'T,': 'Ṭ',

    r"s'": 'ś',
    r"S'": 'Ś',

    r'h,': 'ḫ',
    r'H,': 'Ḫ',

    r'j': 'ŋ',
    r'J': 'Ŋ',

    r'\u02BE': 'ʾ',  # modifier apostrophe (if present)
}

def normalize_atf_characters(text):
    if pd.isna(text):
        return text

    for ascii_pat, uni_char in ATF_ASCII_TO_UNICODE.items():
        text = re.sub(ascii_pat, uni_char, text)

    return text

In [27]:
df['transliteration'] =df['transliteration'].apply(remove_sign_name_markers)

In [28]:
df['translation'] =df['translation'].apply(remove_sign_name_markers)

In [22]:
import pandas as pd

def normalize_subscript_x(text):
    if pd.isna(text):
        return text

    # Unicode subscript x (U+208A) → uppercase X
    text = text.replace('\u208A', 'X')

    return text

In [26]:
import re
import pandas as pd

def remove_sign_name_markers(text):
    if pd.isna(text):
        return text

    # Remove $ or ~ only when they precede an uppercase sign name
    text = re.sub(r'([$~])(?=[A-Z])', '', text)

    return text

In [29]:
df

,transliteration,translation
oare_id,,
004a7dbd-57ce-46f8-9691-409be61c676e,KIŠIB manubalúmašur DUMU ṣílá(d)IM KIŠIB šu(d)...,"Seal of MannumbalumAššur son of ṢilliAdad, sea..."
0064939c-59b9-4448-a63d-34612af0a1b5,1 TÚG ša qátim itur4DINGIR il5qé,Itūrilī has received one textile of ordinary q...
0073f2c0-524c-4bbf-915a-8c1772a4fb98,TÚG ula idínakuum itùrama 9 GÍN KÙBABBAR,he did not give you a textile He returned and ...
009fb838-8038-42bc-ad34-5f795b3840ee,KIŠIB šu(d)ENLÍL DUMU šukubiim KIŠIB ṣílulu DU...,"Seal of ŠuIllil son of ŠuKūbum, seal of Ṣilūlu..."
00aa1c55-c80c-4346-a159-73ad43ab0ff7,umma šukutumma ana IŠTARlámasí ù nitaaḫšušar q...,From Šukkutum to Ištarlamassī and Nitahšušar W...
...,...,...
ff3208e4-8ab8-4368-b4df-7b80afa5bc32,umma ennamašurma ana alaḫiim qíbima anakam adu...,From EnnamAššur to Aliahum Here 2 men have rea...
ff43a284-3d67-4238-8b4a-9b6cb7531e0a,3 mana KÙBABBAR ṣarupáam ina šíim SÍGḪIA ša úš...,Ilīašrannī son of Sukkalliya has received 3 mi...
ff5747a4-af8a-4100-a906-a2660ae72606,šalimašùr ana amurIŠTAR úṭáḫiniatíma umma šali...,ŠalimAššur made us approach AmurIštar and Šali...
ff777871-97ce-4bfc-bdfb-73352868944d,ana ennamašùr qíbima umma IŠTARrabi4atma adí K...,To EnnamAššur from Ištarrabi'at With respect t...
ff9442fd-9e7d-449c-a2d6-0cc35921cd65,umma ša kima ašùrimìtí DUMU ikupíIŠTARma ašùri...,The representatives of Aššurimittī son of Ikūn...

In [30]:
import re
import pandas as pd

def normalize_qualified_x_signs(text):
    if pd.isna(text):
        return text

    # Join qualified signs: ba_x(PI) → ba_xPI , ZAX(LAK384) → ZAXLAK384
    text = re.sub(
        r'([A-Za-z0-9ₓx]+)\(([^)]+)\)',
        r'\1\2',
        text
    )

    return text

In [31]:
df['transliteration'] =df['transliteration'].apply(normalize_qualified_x_signs)

In [44]:
df['translation'] =df['translation'].apply(remove_stopwords)

In [46]:
df.to_csv('stopword_processed.csv')

In [45]:
df

,transliteration,translation
oare_id,,
004a7dbd-57ce-46f8-9691-409be61c676e,KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-(d)IM KIŠI...,"Seal Mannum-balum-Aššur son Ṣilli-Adad, seal..."
0064939c-59b9-4448-a63d-34612af0a1b5,1 TÚG ša qá-tim i-tur₄-DINGIR il₅-qé,Itūr-ilī received one textile ordinary quality.
0073f2c0-524c-4bbf-915a-8c1772a4fb98,TÚG u-la i-dí-na-ku-um i-tù-ra-ma 9 GÍN KÙ.BABBAR,... give textile. He returned 9 shekels ...
009fb838-8038-42bc-ad34-5f795b3840ee,KIŠIB šu-(d)EN.LÍL DUMU šu-ku-bi-im KIŠIB ṣí-l...,"Seal Šu-Illil son Šu-Kūbum, seal Ṣilūlu son..."
00aa1c55-c80c-4346-a159-73ad43ab0ff7,um-ma šu-ku-tum-ma a-na IŠTAR-lá-ma-sí ù ni-ta...,From Šukkutum Ištar-lamassī Nitahšušar: Why ...
...,...,...
ff3208e4-8ab8-4368-b4df-7b80afa5bc32,um-ma en-nam-a-šur-ma a-na a-la-ḫi-im qí-bi-ma...,From Ennam-Aššur Ali-ahum: Here 2 men reache...
ff43a284-3d67-4238-8b4a-9b6cb7531e0a,3 ma-na KÙ.BABBAR ṣa-ru-pá-am i-na ší-im SÍG.Ḫ...,Ilī-ašrannī son Sukkalliya received 3 minas ...
ff5747a4-af8a-4100-a906-a2660ae72606,ša-lim-a-šùr a-na a-mur-IŠTAR ú-ṭá-ḫi-ni-a-tí-...,Šalim-Aššur made us approach Amur-Ištar Šalim...
ff777871-97ce-4bfc-bdfb-73352868944d,a-na en-nam-a-šùr qí-bi-ma um-ma IŠTAR-ra-bi₄-...,To Ennam-Aššur Ištar-rabiʾat: With respect ...
ff9442fd-9e7d-449c-a2d6-0cc35921cd65,um-ma ša ki-ma a-šùr-i-mì-tí DUMU i-ku-pí-IŠTA...,The representatives Aššur-imittī son Ikūn-pī...

In [36]:
from nltk.corpus import stopwords

In [38]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [39]:
from nltk.corpus import stopwords

def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [48]:
from nltk.stem.porter import PorterStemmer

In [49]:
ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [50]:
df['translation'] =df['translation'].apply(stem_words)

In [52]:
df

,transliteration,translation
oare_id,,
004a7dbd-57ce-46f8-9691-409be61c676e,KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-(d)IM KIŠI...,"seal mannum-balum-aššur son ṣilli-adad, seal š..."
0064939c-59b9-4448-a63d-34612af0a1b5,1 TÚG ša qá-tim i-tur₄-DINGIR il₅-qé,itūr-ilī receiv one textil ordinari quality.
0073f2c0-524c-4bbf-915a-8c1772a4fb98,TÚG u-la i-dí-na-ku-um i-tù-ra-ma 9 GÍN KÙ.BABBAR,... give textile. he return 9 shekel silver ...
009fb838-8038-42bc-ad34-5f795b3840ee,KIŠIB šu-(d)EN.LÍL DUMU šu-ku-bi-im KIŠIB ṣí-l...,"seal šu-illil son šu-kūbum, seal ṣilūlu son uk..."
00aa1c55-c80c-4346-a159-73ad43ab0ff7,um-ma šu-ku-tum-ma a-na IŠTAR-lá-ma-sí ù ni-ta...,from šukkutum ištar-lamassī nitahšušar: whi (f...
...,...,...
ff3208e4-8ab8-4368-b4df-7b80afa5bc32,um-ma en-nam-a-šur-ma a-na a-la-ḫi-im qí-bi-ma...,from ennam-aššur ali-ahum: here 2 men reach ag...
ff43a284-3d67-4238-8b4a-9b6cb7531e0a,3 ma-na KÙ.BABBAR ṣa-ru-pá-am i-na ší-im SÍG.Ḫ...,ilī-ašrannī son sukkalliya receiv 3 mina refin...
ff5747a4-af8a-4100-a906-a2660ae72606,ša-lim-a-šùr a-na a-mur-IŠTAR ú-ṭá-ḫi-ni-a-tí-...,šalim-aššur made us approach amur-ištar šalim-...
ff777871-97ce-4bfc-bdfb-73352868944d,a-na en-nam-a-šùr qí-bi-ma um-ma IŠTAR-ra-bi₄-...,to ennam-aššur ištar-rabiʾat: with respect sil...
ff9442fd-9e7d-449c-a2d6-0cc35921cd65,um-ma ša ki-ma a-šùr-i-mì-tí DUMU i-ku-pí-IŠTA...,"the repres aššur-imittī son ikūn-pī-ištar, ašš..."