In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv

In [3]:
train = pd.read_csv('train.csv')
train

,oare_id,transliteration,translation
0,004a7dbd-57ce-46f8-9691-409be61c676e,KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-(d)IM KIŠI...,"Seal of Mannum-balum-Aššur son of Ṣilli-Adad, ..."
1,0064939c-59b9-4448-a63d-34612af0a1b5,1 TÚG ša qá-tim i-tur₄-DINGIR il₅-qé,Itūr-ilī has received one textile of ordinary ...
2,0073f2c0-524c-4bbf-915a-8c1772a4fb98,TÚG u-la i-dí-na-ku-um i-tù-ra-ma 9 GÍN KÙ.BABBAR,... he did not give you a textile. He returned...
3,009fb838-8038-42bc-ad34-5f795b3840ee,KIŠIB šu-(d)EN.LÍL DUMU šu-ku-bi-im KIŠIB ṣí-l...,"Seal of Šu-Illil son of Šu-Kūbum, seal of Ṣilū..."
4,00aa1c55-c80c-4346-a159-73ad43ab0ff7,um-ma šu-ku-tum-ma a-na IŠTAR-lá-ma-sí ù ni-ta...,From Šukkutum to Ištar-lamassī and Nitahšušar:...
...,...,...,...
1556,ff3208e4-8ab8-4368-b4df-7b80afa5bc32,um-ma en-nam-a-šur-ma a-na a-la-ḫi-im qí-bi-ma...,From Ennam-Aššur to Ali-ahum: Here 2 men have ...
1557,ff43a284-3d67-4238-8b4a-9b6cb7531e0a,3 ma-na KÙ.BABBAR ṣa-ru-pá-am i-na ší-im SÍG.Ḫ...,Ilī-ašrannī son of Sukkalliya has received 3 m...
1558,ff5747a4-af8a-4100-a906-a2660ae72606,ša-lim-a-šùr a-na a-mur-IŠTAR ú-ṭá-ḫi-ni-a-tí-...,Šalim-Aššur made us approach Amur-Ištar and Ša...
1559,ff777871-97ce-4bfc-bdfb-73352868944d,a-na en-nam-a-šùr qí-bi-ma um-ma IŠTAR-ra-bi₄-...,To Ennam-Aššur from Ištar-rabiʾat: With respec...
1560,ff9442fd-9e7d-449c-a2d6-0cc35921cd65,um-ma ša ki-ma a-šùr-i-mì-tí DUMU i-ku-pí-IŠTA...,The representatives of Aššur-imittī son of Ikū...

In [4]:
from google.colab import files
uploaded = files.upload()

Saving Sentences_Oare_FirstWord_LinNum.csv to Sentences_Oare_FirstWord_LinNum.csv

In [5]:
sentence_oare = pd.read_csv('Sentences_Oare_FirstWord_LinNum.csv')
sentence_oare

,display_name,text_uuid,sentence_uuid,sentence_obj_in_text,translation,first_word_transcription,first_word_spelling,first_word_number,first_word_obj_in_text,line_number,side,column
0,(Adana 237a) envelope,871e7671-e26b-4808-9acb-1c4a7e1ed2e6,f98879ad-d891-4602-8443-965baab6845d,3,Seal: trading station of Šalatiwar.,NaN,KIŠIB,1,5,1.00,1,1
1,(Adana 237s),09260971-37a9-4b91-aa30-ff59322598e5,e3444ecf-0276-4e5a-90cb-1e08e9d9f65e,3,From Imdī-ilum to Luzina and Puzur-Ištar:,NaN,um-ma,1,5,1.00,1,1
2,(HS 2931),a5abb045-e25a-469a-90b3-89a49091b7be,cb7f723d-6e52-454d-8ca2-50863cab81cb,10,"To the representatives Aššur-imittī, Imdī-ilum...",qibima,qí-bi₄-ma,8,11,3.00,1,1
3,(HS 2931),a5abb045-e25a-469a-90b3-89a49091b7be,5dc308e4-1033-4200-8b8b-6626d155539c,20,Ilī-uṣranni brings you 10 minas refined silver.,Ilī-uṣranni,ì-lí-uṣ-ra-ni,15,21,6.00,1,1
4,(HS 2931),a5abb045-e25a-469a-90b3-89a49091b7be,49ae0d28-4916-4744-b316-607432f9b091,23,Weigh it out to the one you recorded as my gua...,ana,a-na,17,25,8.00,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
9777,VS 26 99 (VAT 9268),ecb81e62-06b0-3ba0-6d4f-9372415c786d,766d0d39-5767-4b98-bb71-d39fce93c908,20,(He will pay) 23? ḫamuštum weeks from the ḫamu...,ištu,iš-tù,11,22,4.00,1,1
9778,VS 26 99 (VAT 9268),ecb81e62-06b0-3ba0-6d4f-9372415c786d,0220fef3-617c-4456-9dcf-d8a6e51bb44e,37,"[If he does not pay at full term, he will add ...",šumma,šu-ma,21,39,8.00,1,1
9779,VS 26 99 (VAT 9268),ecb81e62-06b0-3ba0-6d4f-9372415c786d,dbdfc4e9-420c-4a9f-891d-7147663384c4,53,...,ṭuppam,ṭup-pá-am,29,55,1.01,3,1
9780,VS 26 99 (VAT 9268),ecb81e62-06b0-3ba0-6d4f-9372415c786d,c1cd791f-1451-4d2d-a2e8-70b559c4e895,67,If Uṣur-ša-Aššur does not hand over the tablet...,šumma,šu-ma,38,69,4.01,3,1
9781,VS 26 99 (VAT 9268),ecb81e62-06b0-3ba0-6d4f-9372415c786d,d39e7a66-e0fa-474c-8535-a8f4eaf0a66c,83,Witnesses: (signs partially erased).,maḫar,IGI,47,85,8.01,4,1

In [ ]:
# unique_matches = sentence_oare[
#     sentence_oare['text_uuid'].isin(train['oare_id']) &
#     ~sentence_oare.duplicated(subset='text_uuid', keep='first')
# ].drop_duplicates(subset='text_uuid', keep='first')

In [7]:
sentence_oare.rename(columns={'translation': 'translation_sent'}, inplace=True)

In [8]:
sentence_oare

,display_name,text_uuid,sentence_uuid,sentence_obj_in_text,translation_sent,first_word_transcription,first_word_spelling,first_word_number,first_word_obj_in_text,line_number,side,column
0,(Adana 237a) envelope,871e7671-e26b-4808-9acb-1c4a7e1ed2e6,f98879ad-d891-4602-8443-965baab6845d,3,Seal: trading station of Šalatiwar.,NaN,KIŠIB,1,5,1.00,1,1
1,(Adana 237s),09260971-37a9-4b91-aa30-ff59322598e5,e3444ecf-0276-4e5a-90cb-1e08e9d9f65e,3,From Imdī-ilum to Luzina and Puzur-Ištar:,NaN,um-ma,1,5,1.00,1,1
2,(HS 2931),a5abb045-e25a-469a-90b3-89a49091b7be,cb7f723d-6e52-454d-8ca2-50863cab81cb,10,"To the representatives Aššur-imittī, Imdī-ilum...",qibima,qí-bi₄-ma,8,11,3.00,1,1
3,(HS 2931),a5abb045-e25a-469a-90b3-89a49091b7be,5dc308e4-1033-4200-8b8b-6626d155539c,20,Ilī-uṣranni brings you 10 minas refined silver.,Ilī-uṣranni,ì-lí-uṣ-ra-ni,15,21,6.00,1,1
4,(HS 2931),a5abb045-e25a-469a-90b3-89a49091b7be,49ae0d28-4916-4744-b316-607432f9b091,23,Weigh it out to the one you recorded as my gua...,ana,a-na,17,25,8.00,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
9777,VS 26 99 (VAT 9268),ecb81e62-06b0-3ba0-6d4f-9372415c786d,766d0d39-5767-4b98-bb71-d39fce93c908,20,(He will pay) 23? ḫamuštum weeks from the ḫamu...,ištu,iš-tù,11,22,4.00,1,1
9778,VS 26 99 (VAT 9268),ecb81e62-06b0-3ba0-6d4f-9372415c786d,0220fef3-617c-4456-9dcf-d8a6e51bb44e,37,"[If he does not pay at full term, he will add ...",šumma,šu-ma,21,39,8.00,1,1
9779,VS 26 99 (VAT 9268),ecb81e62-06b0-3ba0-6d4f-9372415c786d,dbdfc4e9-420c-4a9f-891d-7147663384c4,53,...,ṭuppam,ṭup-pá-am,29,55,1.01,3,1
9780,VS 26 99 (VAT 9268),ecb81e62-06b0-3ba0-6d4f-9372415c786d,c1cd791f-1451-4d2d-a2e8-70b559c4e895,67,If Uṣur-ša-Aššur does not hand over the tablet...,šumma,šu-ma,38,69,4.01,3,1
9781,VS 26 99 (VAT 9268),ecb81e62-06b0-3ba0-6d4f-9372415c786d,d39e7a66-e0fa-474c-8535-a8f4eaf0a66c,83,Witnesses: (signs partially erased).,maḫar,IGI,47,85,8.01,4,1

In [9]:
matched_df = sentence_oare.merge(
    train[['oare_id', 'translation', 'transliteration']],  
    left_on='text_uuid',
    right_on='oare_id',
    how='inner'
)


final_df = matched_df[[
    'oare_id',
    'text_uuid',
    'translation_sent',  
    'translation',
    'transliteration',    
    'first_word_spelling',
    'first_word_number',
    'first_word_obj_in_text',
    'line_number',
    'side',
    'column' 
]].copy()

final_df

,oare_id,text_uuid,translation_sent,translation,transliteration,first_word_spelling,first_word_number,first_word_obj_in_text,line_number,side,column
0,f352e4ba-65ff-43bf-88ce-8e3e073943be,f352e4ba-65ff-43bf-88ce-8e3e073943be,Ennanim s. Azua owes Elamma 2 minas refined si...,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ša,1,5,1.0,1,1
1,f352e4ba-65ff-43bf-88ce-8e3e073943be,f352e4ba-65ff-43bf-88ce-8e3e073943be,Month: ša kēnātim.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ITU.1.KAM,12,25,5.0,1,1
2,f352e4ba-65ff-43bf-88ce-8e3e073943be,f352e4ba-65ff-43bf-88ce-8e3e073943be,Eponymate: after Aššur-damiq s. Abarsisin.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,li-mu-um,15,31,6.0,1,1
3,f352e4ba-65ff-43bf-88ce-8e3e073943be,f352e4ba-65ff-43bf-88ce-8e3e073943be,Ḫamuštum: Aššur-imittī s. Attaya.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ḫa-muš-tum,21,43,8.0,1,1
4,f352e4ba-65ff-43bf-88ce-8e3e073943be,f352e4ba-65ff-43bf-88ce-8e3e073943be,He will pay 2/3 minas in one year.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ma-na.TA,27,55,9.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...
1208,3a1e965b-3b71-452c-84a2-7416f7cdf986,3a1e965b-3b71-452c-84a2-7416f7cdf986,Before the land has heard it you must withdraw...,From Ali-ahum to Damiq-pī-Aššur: Elāli and Enn...,um-ma a-lá-ḫu-um-ma a-na SIG₅-pì-i-a-šur qí-bi...,lá-ma,30,48,11.0,1,1
1209,52a72ed1-d6fe-4d58-85d4-987937084fc0,52a72ed1-d6fe-4d58-85d4-987937084fc0,From,From Kudātum and Man-mahir to Ennam-Aššur: Man...,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,um-ma,1,4,1.0,1,1
1210,52a72ed1-d6fe-4d58-85d4-987937084fc0,52a72ed1-d6fe-4d58-85d4-987937084fc0,Mannum-kī-Aššur,From Kudātum and Man-mahir to Ennam-Aššur: Man...,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,ku-nu-ki-šu-nu,17,23,7.0,1,1
1211,52a72ed1-d6fe-4d58-85d4-987937084fc0,52a72ed1-d6fe-4d58-85d4-987937084fc0,Have,From Kudātum and Man-mahir to Ennam-Aššur: Man...,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,a-ma-kam,22,32,11.0,3,1
1212,9b14060a-4325-4e83-aab8-2e717d743480,9b14060a-4325-4e83-aab8-2e717d743480,The plenary assembly of the colony passed a ve...,The plenary assembly of the colony passed a ve...,kà-ru-um ṣa-ḫe-er GAL dí-nam i-dí-in-ma ša-lim...,kà-ru-um,1,3,1.0,1,1

In [ ]:
final_df['transliteration'][0]

'ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na-nim DUMU a-zu-a e-la-ma i-šu ITU.1.KAM ša ke-na-tim li-mu-um ša qá-tí a-šùr-SIG₅ DUMU a-bar-sí-sí-im ḫa-muš-tum ša a-šur-mì-tí DUMU a-ta-a 0.66666 ma-na.TA i-na ša-tim i-ša-qal šu-ma lá iš-qúl 1.5 GÍN.TA ṣí-ib-tám a-na 1 ma-na-im i ITU.1.KAM ú-ṣa-áb IGI e-na-a-nim IGI la-qé-pì-im a-na 11 (TÚG)ku-ta-ni a-mur-IŠTAR ù a-la-ḫi-im a-na e-la-ma a-šùr-la-ma-sí a-na ITU.5.KAM ú-kà-an šu-ma lá uk-ta-in-šu-nu 0.33333 ma-na 5 GÍN.TA KÙ.BABBAR ṣa-ru-pá-am a-na e-lá-ma a-šùr-la-ma-sí i-ša-qal ITU.1.KAM ṣí-ip-um li-mu-um PUZUR₄-(d)MU IGI a-bu-sa-lim DUMU i-dí-ìr-ra IGI i-dí-a-šùr DUMU pu-ur-sí-sí-im'

In [ ]:
final_df[final_df['oare_id'] == 'f352e4ba-65ff-43bf-88ce-8e3e073943be']

,oare_id,text_uuid,translation_sent,translation,transliteration,first_word_spelling,first_word_number,first_word_obj_in_text,line_number,side,column
0,f352e4ba-65ff-43bf-88ce-8e3e073943be,f352e4ba-65ff-43bf-88ce-8e3e073943be,Ennanim s. Azua owes Elamma 2 minas refined si...,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ša,1,5,1.0,1,1
1,f352e4ba-65ff-43bf-88ce-8e3e073943be,f352e4ba-65ff-43bf-88ce-8e3e073943be,Month: ša kēnātim.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ITU.1.KAM,12,25,5.0,1,1
2,f352e4ba-65ff-43bf-88ce-8e3e073943be,f352e4ba-65ff-43bf-88ce-8e3e073943be,Eponymate: after Aššur-damiq s. Abarsisin.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,li-mu-um,15,31,6.0,1,1
3,f352e4ba-65ff-43bf-88ce-8e3e073943be,f352e4ba-65ff-43bf-88ce-8e3e073943be,Ḫamuštum: Aššur-imittī s. Attaya.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ḫa-muš-tum,21,43,8.0,1,1
4,f352e4ba-65ff-43bf-88ce-8e3e073943be,f352e4ba-65ff-43bf-88ce-8e3e073943be,He will pay 2/3 minas in one year.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ma-na.TA,27,55,9.0,1,1
5,f352e4ba-65ff-43bf-88ce-8e3e073943be,f352e4ba-65ff-43bf-88ce-8e3e073943be,"If he does not pay, he will add interest at th...","That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,šu-ma,31,62,11.0,1,1
6,f352e4ba-65ff-43bf-88ce-8e3e073943be,f352e4ba-65ff-43bf-88ce-8e3e073943be,"Witnesses: Ennanim, Lā-qēpim.","That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,IGI,43,84,14.0,2,1
7,f352e4ba-65ff-43bf-88ce-8e3e073943be,f352e4ba-65ff-43bf-88ce-8e3e073943be,"Witnesses: Abu-šalim s. Idari, Idī-Aššur s. pu...","That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,IGI,76,129,29.0,4,1

In [10]:
import pandas as pd
import numpy as np

def add_para_to_sentence(df: pd.DataFrame) -> pd.DataFrame:
    """
    Adds 'para_to_sentence' column by splitting transliteration paragraphs into sentences.

    Assumes:
    - Rows with same text_uuid share the same transliteration paragraph.
    - first_word_number and first_word_obj_in_text are 1-based word indices (int or NaN).
    - Multiple rows per paragraph define all sentence starts collectively.
    """
    def process_group(group: pd.DataFrame) -> pd.DataFrame:
        if len(group) == 0:
            return group

        para_text = group['transliteration'].iloc[0]
        tokens = para_text.split()
        n_tokens = len(tokens)

        
        valid_starts_1based = []
        for _, row in group.iterrows():
            start_num = int(row['first_word_number'])
            obj_num = row['first_word_obj_in_text']
            if pd.isna(obj_num) or int(obj_num) != start_num:
                valid_starts_1based.append(start_num)

        valid_starts_1based = sorted(set([s for s in valid_starts_1based if s <= n_tokens]))

        
        all_sentences = []
        for i, start in enumerate(valid_starts_1based):
            end = valid_starts_1based[i + 1] if i + 1 < len(valid_starts_1based) else n_tokens + 1
            sent_tokens = tokens[start - 1 : end - 1]
            all_sentences.append(' '.join(sent_tokens))

        
        result = group.copy()
        for idx, row in result.iterrows():
            start_num = int(row['first_word_number'])
            for s_idx, s_start in enumerate(valid_starts_1based):
                if s_start == start_num:
                    result.at[idx, 'para_to_sentence'] = all_sentences[s_idx]
                    break
            else:
                result.at[idx, 'para_to_sentence'] = ''  

        return result

    
    return df.groupby('text_uuid', group_keys=False).apply(process_group, include_groups=False).reset_index(drop=True)


result_df = add_para_to_sentence(final_df)

In [11]:
result_df['para_to_sentence'][6]

'IGI e-na-a-nim IGI la-qé-pì-im a-na 11 (TÚG)ku-ta-ni a-mur-IŠTAR ù a-la-ḫi-im a-na e-la-ma a-šùr-la-ma-sí a-na ITU.5.KAM ú-kà-an šu-ma lá uk-ta-in-šu-nu 0.33333 ma-na 5 GÍN.TA KÙ.BABBAR ṣa-ru-pá-am a-na e-lá-ma a-šùr-la-ma-sí i-ša-qal ITU.1.KAM ṣí-ip-um li-mu-um PUZUR₄-(d)MU'

In [12]:
result_df.shape

(1213, 11)

In [13]:
result_df.columns

Index(['oare_id', 'translation_sent', 'translation', 'transliteration',
       'first_word_spelling', 'first_word_number', 'first_word_obj_in_text',
       'line_number', 'side', 'column', 'para_to_sentence'],
      dtype='object')

In [14]:
result_df['translation_sent'].iloc[0:8]

0    Ennanim s. Azua owes Elamma 2 minas refined si...
1                                  Month: ša kēnātim.
2          Eponymate: after Aššur-damiq s. Abarsisin.
3                   Ḫamuštum: Aššur-imittī s. Attaya.
4                  He will pay 2/3 minas in one year.
5    If he does not pay, he will add interest at th...
6                       Witnesses: Ennanim, Lā-qēpim.
7    Witnesses: Abu-šalim s. Idari, Idī-Aššur s. pu...
Name: translation_sent, dtype: object

In [15]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.2.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.57.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.9.0+cpu)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (0.36.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.11.12)

In [16]:
import pandas as pd
from sentence_transformers import SentenceTransformer, util
import numpy as np


def validate_sentence_reconstruction(df: pd.DataFrame) -> pd.DataFrame:
    """
    For each oare_id:
    1. Concat all translation_sent → combined_sent
    2. Compare combined_sent vs translation via cosine similarity
    """
  
    if df['translation_sent'].dtype == 'object':
        df['translation_sent_flat'] = df['translation_sent'].apply(
            lambda x: ' '.join(x) if isinstance(x, list) else str(x)
        )
    else:
        df['translation_sent_flat'] = df['translation_sent'].astype(str)

    
    grouped = df.groupby('oare_id').agg({
        'translation_sent_flat': lambda x: ' '.join(x.dropna().unique()),  
        'translation': 'first'  
    }).reset_index()

    
    model = SentenceTransformer('all-MiniLM-L6-v2')
    combined_sents = grouped['translation_sent_flat'].tolist()
    para_trans = grouped['translation'].dropna().tolist()

    if combined_sents:
        embeds1 = model.encode(combined_sents, show_progress_bar=True)
        embeds2 = model.encode(para_trans, show_progress_bar=True)
        similarities = util.pytorch_cos_sim(embeds1, embeds2).diag().cpu().numpy()
        grouped['similarity_score'] = similarities
    else:
        grouped['similarity_score'] = np.nan

    return grouped[['oare_id', 'similarity_score', 'translation_sent_flat', 'translation']]


result_df_2 = validate_sentence_reconstruction(result_df)
print(result_df_2[['oare_id', 'similarity_score']].round(3))

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

                                  oare_id  similarity_score
0    004a7dbd-57ce-46f8-9691-409be61c676e             0.890
1    009fb838-8038-42bc-ad34-5f795b3840ee             0.970
2    0126cd13-acf7-4cd5-8373-f1e7b54d824e             0.973
3    01cc1406-fc42-4252-aeae-6b4538b069c5             0.996
4    020aa8bd-69a4-43a9-8120-efd9e587bb1c             0.267
..                                    ...               ...
248  fca76fd0-dbb1-42f5-a978-fc683270e374             0.863
249  fd482abc-8de7-4157-88c4-f1a3e80f5a67             0.704
250  fded4d2f-81a5-45b3-8d62-74e5ffb2e159             0.989
251  fe0b8448-f09e-47cf-b1e8-8e8d96531bb3             0.524
252  ff43a284-3d67-4238-8b4a-9b6cb7531e0a             1.000

[253 rows x 2 columns]

In [41]:
result_df.drop(columns=['translation_sent_flat'], axis=1, inplace=True)
result_df

,oare_id,translation_sent,translation,transliteration,first_word_spelling,first_word_number,first_word_obj_in_text,line_number,side,column,para_to_sentence
0,f352e4ba-65ff-43bf-88ce-8e3e073943be,Ennanim s. Azua owes Elamma 2 minas refined si...,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ša,1,5,1.0,1,1,ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...
1,f352e4ba-65ff-43bf-88ce-8e3e073943be,Month: ša kēnātim.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ITU.1.KAM,12,25,5.0,1,1,ITU.1.KAM ša ke-na-tim
2,f352e4ba-65ff-43bf-88ce-8e3e073943be,Eponymate: after Aššur-damiq s. Abarsisin.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,li-mu-um,15,31,6.0,1,1,li-mu-um ša qá-tí a-šùr-SIG₅ DUMU a-bar-sí-sí-im
3,f352e4ba-65ff-43bf-88ce-8e3e073943be,Ḫamuštum: Aššur-imittī s. Attaya.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ḫa-muš-tum,21,43,8.0,1,1,ḫa-muš-tum ša a-šur-mì-tí DUMU a-ta-a 0.66666
4,f352e4ba-65ff-43bf-88ce-8e3e073943be,He will pay 2/3 minas in one year.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ma-na.TA,27,55,9.0,1,1,ma-na.TA i-na ša-tim i-ša-qal
...,...,...,...,...,...,...,...,...,...,...,...
1208,3a1e965b-3b71-452c-84a2-7416f7cdf986,Before the land has heard it you must withdraw...,From Ali-ahum to Damiq-pī-Aššur: Elāli and Enn...,um-ma a-lá-ḫu-um-ma a-na SIG₅-pì-i-a-šur qí-bi...,lá-ma,30,48,11.0,1,1,lá-ma ma-tum iš-me-ú ra-ma-ku-nu šu-ul-ḫa-a 1 ...
1209,52a72ed1-d6fe-4d58-85d4-987937084fc0,From,From Kudātum and Man-mahir to Ennam-Aššur: Man...,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,um-ma,1,4,1.0,1,1,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...
1210,52a72ed1-d6fe-4d58-85d4-987937084fc0,Mannum-kī-Aššur,From Kudātum and Man-mahir to Ennam-Aššur: Man...,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,ku-nu-ki-šu-nu,17,23,7.0,1,1,ku-nu-ki-šu-nu ma-nu-um-ki-a-šur DUMU a-ḫu-wa-...
1211,52a72ed1-d6fe-4d58-85d4-987937084fc0,Have,From Kudātum and Man-mahir to Ennam-Aššur: Man...,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,a-ma-kam,22,32,11.0,3,1,a-ma-kam KÙ.BABBAR li-iš-qú-lá-ku-ma ú ṭup-pá-...
1212,9b14060a-4325-4e83-aab8-2e717d743480,The plenary assembly of the colony passed a ve...,The plenary assembly of the colony passed a ve...,kà-ru-um ṣa-ḫe-er GAL dí-nam i-dí-in-ma ša-lim...,kà-ru-um,1,3,1.0,1,1,kà-ru-um ṣa-ḫe-er GAL dí-nam i-dí-in-ma ša-lim...

In [39]:
result_df_2

,oare_id,similarity_score,translation_sent_flat,translation
0,004a7dbd-57ce-46f8-9691-409be61c676e,0.890118,"Seals of Mannum-bālum-Aššur s. ?, Šū-Enlil s. ...","Seal of Mannum-balum-Aššur son of Ṣilli-Adad, ..."
1,009fb838-8038-42bc-ad34-5f795b3840ee,0.970273,"Seal of Šu-Illil son of Šu-kūbum, seal of Şilū...","Seal of Šu-Illil son of Šu-Kūbum, seal of Ṣilū..."
2,0126cd13-acf7-4cd5-8373-f1e7b54d824e,0.972886,We entered Šalim-Aššur's house to settle the c...,We entered Šalim-Aššur's house to settle the c...
3,01cc1406-fc42-4252-aeae-6b4538b069c5,0.996024,"17 shekels of silver, the price of a donkey, 3...","17 shekels of silver, the price of a donkey, 3..."
4,020aa8bd-69a4-43a9-8120-efd9e587bb1c,0.266835,"Witnesses: Aššur-idī, Elāli; Puzur-ilī son of ...","Ikūn-pīya and Ennam-Aššur seized us, and Ikūn-..."
...,...,...,...,...
248,fca76fd0-dbb1-42f5-a978-fc683270e374,0.862701,Puzur-Ištar owes 1/3 minas minus 2 shekels ref...,Puzur-Ištar owes 0.3333 mina less 2 shekels of...
249,fd482abc-8de7-4157-88c4-f1a3e80f5a67,0.704026,To Ali-aḫum from Puzur-Aššur: 48 nan But the c...,To Ali-ahum from Puzur-Aššur: 48 good textiles...
250,fded4d2f-81a5-45b3-8d62-74e5ffb2e159,0.988610,"Seal of Kula brother of Šukkutum, seal of Puzu...","Seal of Kula brother of Šukkutum, seal of Puzu..."
251,fe0b8448-f09e-47cf-b1e8-8e8d96531bb3,0.523545,"To Adida, Al-aḫum and Uku from Puzur-Aššur To ...","To Adida, Ali-ahum, and Uku from Puzur-Aššur: ..."
252,ff43a284-3d67-4238-8b4a-9b6cb7531e0a,1.000000,Ilī-ašrannī son of Sukkalliya has received 3 m...,Ilī-ašrannī son of Sukkalliya has received 3 m...

In [17]:
result_df_2[result_df_2['similarity_score'] <= 0.85]

,oare_id,similarity_score,translation_sent_flat,translation
4,020aa8bd-69a4-43a9-8120-efd9e587bb1c,0.266835,"Witnesses: Aššur-idī, Elāli; Puzur-ilī son of ...","Ikūn-pīya and Ennam-Aššur seized us, and Ikūn-..."
7,03afa072-8f71-4403-b303-086f6097db3f,0.835230,--a-šur owes the merchant 4 shekels silver. H...,4 shekels of silver [... ... ...-Aš]šur owes t...
8,041c9029-8f6f-40f8-989b-77a75878221c,0.471508,To Al-aḫum from Puzur-Aššur:,To Ali-ahum from Puzur-Aššur: 0.5 mina of silv...
12,091abe17-bf55-4912-b402-15442365622a,0.346847,To Al-aḫum and Zukuwa from Puzur-Aššur:,To Ali-ahum and Zukuwa from Puzur-Aššur: Ennam...
15,0afc88d2-258e-4d6a-8c02-25b605573093,0.599350,Aššur-imittī Witnessed by Ennam-Wēr son of Šud...,Aššur-imittī son of Etaya has received 17 mina...
...,...,...,...,...
242,f57b8fce-716d-4d0c-a0ba-bdabaa6584ae,0.809110,...son of Edišin ... for 10 years (interest) w...,14.5 shekels of silver is owed by Ilī-dan son ...
244,f885d25c-852a-44e7-8aec-e58a6417eb5a,0.403575,"To Dadaya, Al-aḫum and Enlil-bāni from Puzur-A...","To Dadaya, Ali-ahum and Illil-bāni from Puzur-..."
247,fc678a23-7011-4f9d-8957-ebf2c8dbbb43,0.154338,"Of further,",Of the copper belonging to Man-mahir which Enn...
249,fd482abc-8de7-4157-88c4-f1a3e80f5a67,0.704026,To Ali-aḫum from Puzur-Aššur: 48 nan But the c...,To Ali-ahum from Puzur-Aššur: 48 good textiles...
251,fe0b8448-f09e-47cf-b1e8-8e8d96531bb3,0.523545,"To Adida, Al-aḫum and Uku from Puzur-Aššur To ...","To Adida, Ali-ahum, and Uku from Puzur-Aššur: ..."

In [22]:
result_df_2.iloc[12]['translation_sent_flat']

'To Al-aḫum and Zukuwa from Puzur-Aššur:'

In [21]:
result_df_2.iloc[12]['translation']

'To Ali-ahum and Zukuwa from Puzur-Aššur: Ennam-Aššur brought 13 minas of tin there. My dear brothers, if he has given you the tin, then seal the tin and send it here. If he has given you silver together with the tin, then make a profitable purchase for me and send it here with the very first travellers. If Damqaya is on his way to the City, then give him a mina of silver, and just as I brought up tin for him, he too should bring up tin without deductions for me.'

In [ ]:
result_df_2 = result_df_2[result_df_2['similarity_score'] > 0.7]

In [23]:
result_df[result_df['oare_id'] == '091abe17-bf55-4912-b402-15442365622a']

,oare_id,translation_sent,translation,transliteration,first_word_spelling,first_word_number,first_word_obj_in_text,line_number,side,column,para_to_sentence,translation_sent_flat
1127,091abe17-bf55-4912-b402-15442365622a,To Al-aḫum and Zukuwa from Puzur-Aššur:,To Ali-ahum and Zukuwa from Puzur-Aššur: Ennam...,a-na a-lá-ḫi-im ú zu-ku-a qí-bi-ma um-ma PUZUR...,a-na,1,5,1.0,1,1,a-na a-lá-ḫi-im ú zu-ku-a qí-bi-ma um-ma PUZUR...,To Al-aḫum and Zukuwa from Puzur-Aššur:

In [24]:
sentence_oare[sentence_oare['text_uuid'] == '091abe17-bf55-4912-b402-15442365622a']

,display_name,text_uuid,sentence_uuid,sentence_obj_in_text,translation_sent,first_word_transcription,first_word_spelling,first_word_number,first_word_obj_in_text,line_number,side,column
5740,Kt 94/k 888b (AKT 6c 580),091abe17-bf55-4912-b402-15442365622a,65a99ebd-0c95-4d73-8fa7-9cbd9d0f8fd1,3,To Al-aḫum and Zukuwa from Puzur-Aššur:,ana,a-na,1,5,1.0,1,1

In [42]:
result_df_merged = result_df.merge(result_df_2, on='oare_id', how='left')
result_df_merged

,oare_id,translation_sent,translation_x,transliteration,first_word_spelling,first_word_number,first_word_obj_in_text,line_number,side,column,para_to_sentence,similarity_score,translation_sent_flat,translation_y
0,f352e4ba-65ff-43bf-88ce-8e3e073943be,Ennanim s. Azua owes Elamma 2 minas refined si...,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ša,1,5,1.0,1,1,ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,0.805540,Ennanim s. Azua owes Elamma 2 minas refined si...,"That Ennānum, son of Azua, owes 2 minas of ref..."
1,f352e4ba-65ff-43bf-88ce-8e3e073943be,Month: ša kēnātim.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ITU.1.KAM,12,25,5.0,1,1,ITU.1.KAM ša ke-na-tim,0.805540,Ennanim s. Azua owes Elamma 2 minas refined si...,"That Ennānum, son of Azua, owes 2 minas of ref..."
2,f352e4ba-65ff-43bf-88ce-8e3e073943be,Eponymate: after Aššur-damiq s. Abarsisin.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,li-mu-um,15,31,6.0,1,1,li-mu-um ša qá-tí a-šùr-SIG₅ DUMU a-bar-sí-sí-im,0.805540,Ennanim s. Azua owes Elamma 2 minas refined si...,"That Ennānum, son of Azua, owes 2 minas of ref..."
3,f352e4ba-65ff-43bf-88ce-8e3e073943be,Ḫamuštum: Aššur-imittī s. Attaya.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ḫa-muš-tum,21,43,8.0,1,1,ḫa-muš-tum ša a-šur-mì-tí DUMU a-ta-a 0.66666,0.805540,Ennanim s. Azua owes Elamma 2 minas refined si...,"That Ennānum, son of Azua, owes 2 minas of ref..."
4,f352e4ba-65ff-43bf-88ce-8e3e073943be,He will pay 2/3 minas in one year.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ma-na.TA,27,55,9.0,1,1,ma-na.TA i-na ša-tim i-ša-qal,0.805540,Ennanim s. Azua owes Elamma 2 minas refined si...,"That Ennānum, son of Azua, owes 2 minas of ref..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1208,3a1e965b-3b71-452c-84a2-7416f7cdf986,Before the land has heard it you must withdraw...,From Ali-ahum to Damiq-pī-Aššur: Elāli and Enn...,um-ma a-lá-ḫu-um-ma a-na SIG₅-pì-i-a-šur qí-bi...,lá-ma,30,48,11.0,1,1,lá-ma ma-tum iš-me-ú ra-ma-ku-nu šu-ul-ḫa-a 1 ...,0.714447,From Ali-ahum to Damiq-pī-Aššur: Elāli and Enn...,From Ali-ahum to Damiq-pī-Aššur: Elāli and Enn...
1209,52a72ed1-d6fe-4d58-85d4-987937084fc0,From,From Kudātum and Man-mahir to Ennam-Aššur: Man...,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,um-ma,1,4,1.0,1,1,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,0.478974,From Mannum-kī-Aššur Have,From Kudātum and Man-mahir to Ennam-Aššur: Man...
1210,52a72ed1-d6fe-4d58-85d4-987937084fc0,Mannum-kī-Aššur,From Kudātum and Man-mahir to Ennam-Aššur: Man...,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,ku-nu-ki-šu-nu,17,23,7.0,1,1,ku-nu-ki-šu-nu ma-nu-um-ki-a-šur DUMU a-ḫu-wa-...,0.478974,From Mannum-kī-Aššur Have,From Kudātum and Man-mahir to Ennam-Aššur: Man...
1211,52a72ed1-d6fe-4d58-85d4-987937084fc0,Have,From Kudātum and Man-mahir to Ennam-Aššur: Man...,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,a-ma-kam,22,32,11.0,3,1,a-ma-kam KÙ.BABBAR li-iš-qú-lá-ku-ma ú ṭup-pá-...,0.478974,From Mannum-kī-Aššur Have,From Kudātum and Man-mahir to Ennam-Aššur: Man...
1212,9b14060a-4325-4e83-aab8-2e717d743480,The plenary assembly of the colony passed a ve...,The plenary assembly of the colony passed a ve...,kà-ru-um ṣa-ḫe-er GAL dí-nam i-dí-in-ma ša-lim...,kà-ru-um,1,3,1.0,1,1,kà-ru-um ṣa-ḫe-er GAL dí-nam i-dí-in-ma ša-lim...,0.998512,The plenary assembly of the colony passed a ve...,The plenary assembly of the colony passed a ve...

In [43]:
result_df_merged.drop(columns=['translation_y'], axis=1, inplace=True)
result_df_merged.rename(columns={'translation_x': 'translation'}, inplace=True)
result_df_merged

,oare_id,translation_sent,translation,transliteration,first_word_spelling,first_word_number,first_word_obj_in_text,line_number,side,column,para_to_sentence,similarity_score,translation_sent_flat
0,f352e4ba-65ff-43bf-88ce-8e3e073943be,Ennanim s. Azua owes Elamma 2 minas refined si...,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ša,1,5,1.0,1,1,ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,0.805540,Ennanim s. Azua owes Elamma 2 minas refined si...
1,f352e4ba-65ff-43bf-88ce-8e3e073943be,Month: ša kēnātim.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ITU.1.KAM,12,25,5.0,1,1,ITU.1.KAM ša ke-na-tim,0.805540,Ennanim s. Azua owes Elamma 2 minas refined si...
2,f352e4ba-65ff-43bf-88ce-8e3e073943be,Eponymate: after Aššur-damiq s. Abarsisin.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,li-mu-um,15,31,6.0,1,1,li-mu-um ša qá-tí a-šùr-SIG₅ DUMU a-bar-sí-sí-im,0.805540,Ennanim s. Azua owes Elamma 2 minas refined si...
3,f352e4ba-65ff-43bf-88ce-8e3e073943be,Ḫamuštum: Aššur-imittī s. Attaya.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ḫa-muš-tum,21,43,8.0,1,1,ḫa-muš-tum ša a-šur-mì-tí DUMU a-ta-a 0.66666,0.805540,Ennanim s. Azua owes Elamma 2 minas refined si...
4,f352e4ba-65ff-43bf-88ce-8e3e073943be,He will pay 2/3 minas in one year.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ma-na.TA,27,55,9.0,1,1,ma-na.TA i-na ša-tim i-ša-qal,0.805540,Ennanim s. Azua owes Elamma 2 minas refined si...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1208,3a1e965b-3b71-452c-84a2-7416f7cdf986,Before the land has heard it you must withdraw...,From Ali-ahum to Damiq-pī-Aššur: Elāli and Enn...,um-ma a-lá-ḫu-um-ma a-na SIG₅-pì-i-a-šur qí-bi...,lá-ma,30,48,11.0,1,1,lá-ma ma-tum iš-me-ú ra-ma-ku-nu šu-ul-ḫa-a 1 ...,0.714447,From Ali-ahum to Damiq-pī-Aššur: Elāli and Enn...
1209,52a72ed1-d6fe-4d58-85d4-987937084fc0,From,From Kudātum and Man-mahir to Ennam-Aššur: Man...,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,um-ma,1,4,1.0,1,1,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,0.478974,From Mannum-kī-Aššur Have
1210,52a72ed1-d6fe-4d58-85d4-987937084fc0,Mannum-kī-Aššur,From Kudātum and Man-mahir to Ennam-Aššur: Man...,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,ku-nu-ki-šu-nu,17,23,7.0,1,1,ku-nu-ki-šu-nu ma-nu-um-ki-a-šur DUMU a-ḫu-wa-...,0.478974,From Mannum-kī-Aššur Have
1211,52a72ed1-d6fe-4d58-85d4-987937084fc0,Have,From Kudātum and Man-mahir to Ennam-Aššur: Man...,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,a-ma-kam,22,32,11.0,3,1,a-ma-kam KÙ.BABBAR li-iš-qú-lá-ku-ma ú ṭup-pá-...,0.478974,From Mannum-kī-Aššur Have
1212,9b14060a-4325-4e83-aab8-2e717d743480,The plenary assembly of the colony passed a ve...,The plenary assembly of the colony passed a ve...,kà-ru-um ṣa-ḫe-er GAL dí-nam i-dí-in-ma ša-lim...,kà-ru-um,1,3,1.0,1,1,kà-ru-um ṣa-ḫe-er GAL dí-nam i-dí-in-ma ša-lim...,0.998512,The plenary assembly of the colony passed a ve...

In [57]:
result_df_merged

,oare_id,translation_sent,translation,transliteration,first_word_spelling,first_word_number,first_word_obj_in_text,line_number,side,column,para_to_sentence,similarity_score,translation_sent_flat
0,f352e4ba-65ff-43bf-88ce-8e3e073943be,Ennanim s. Azua owes Elamma 2 minas refined si...,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ša,1,5,1.0,1,1,ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,0.805540,Ennanim s. Azua owes Elamma 2 minas refined si...
1,f352e4ba-65ff-43bf-88ce-8e3e073943be,Month: ša kēnātim.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ITU.1.KAM,12,25,5.0,1,1,ITU.1.KAM ša ke-na-tim,0.805540,Ennanim s. Azua owes Elamma 2 minas refined si...
2,f352e4ba-65ff-43bf-88ce-8e3e073943be,Eponymate: after Aššur-damiq s. Abarsisin.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,li-mu-um,15,31,6.0,1,1,li-mu-um ša qá-tí a-šùr-SIG₅ DUMU a-bar-sí-sí-im,0.805540,Ennanim s. Azua owes Elamma 2 minas refined si...
3,f352e4ba-65ff-43bf-88ce-8e3e073943be,Ḫamuštum: Aššur-imittī s. Attaya.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ḫa-muš-tum,21,43,8.0,1,1,ḫa-muš-tum ša a-šur-mì-tí DUMU a-ta-a 0.66666,0.805540,Ennanim s. Azua owes Elamma 2 minas refined si...
4,f352e4ba-65ff-43bf-88ce-8e3e073943be,He will pay 2/3 minas in one year.,"That Ennānum, son of Azua, owes 2 minas of ref...",ša 2 ma-na KÙ.BABBAR ṣa-ru-pá-am i-ṣé-er en-na...,ma-na.TA,27,55,9.0,1,1,ma-na.TA i-na ša-tim i-ša-qal,0.805540,Ennanim s. Azua owes Elamma 2 minas refined si...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1208,3a1e965b-3b71-452c-84a2-7416f7cdf986,Before the land has heard it you must withdraw...,From Ali-ahum to Damiq-pī-Aššur: Elāli and Enn...,um-ma a-lá-ḫu-um-ma a-na SIG₅-pì-i-a-šur qí-bi...,lá-ma,30,48,11.0,1,1,lá-ma ma-tum iš-me-ú ra-ma-ku-nu šu-ul-ḫa-a 1 ...,0.714447,From Ali-ahum to Damiq-pī-Aššur: Elāli and Enn...
1209,52a72ed1-d6fe-4d58-85d4-987937084fc0,From,From Kudātum and Man-mahir to Ennam-Aššur: Man...,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,um-ma,1,4,1.0,1,1,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,0.478974,From Mannum-kī-Aššur Have
1210,52a72ed1-d6fe-4d58-85d4-987937084fc0,Mannum-kī-Aššur,From Kudātum and Man-mahir to Ennam-Aššur: Man...,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,ku-nu-ki-šu-nu,17,23,7.0,1,1,ku-nu-ki-šu-nu ma-nu-um-ki-a-šur DUMU a-ḫu-wa-...,0.478974,From Mannum-kī-Aššur Have
1211,52a72ed1-d6fe-4d58-85d4-987937084fc0,Have,From Kudātum and Man-mahir to Ennam-Aššur: Man...,um-ma ku-da-tum ú ma-ma-ḫi-ir-ma a-na e-nam-a-...,a-ma-kam,22,32,11.0,3,1,a-ma-kam KÙ.BABBAR li-iš-qú-lá-ku-ma ú ṭup-pá-...,0.478974,From Mannum-kī-Aššur Have
1212,9b14060a-4325-4e83-aab8-2e717d743480,The plenary assembly of the colony passed a ve...,The plenary assembly of the colony passed a ve...,kà-ru-um ṣa-ḫe-er GAL dí-nam i-dí-in-ma ša-lim...,kà-ru-um,1,3,1.0,1,1,kà-ru-um ṣa-ḫe-er GAL dí-nam i-dí-in-ma ša-lim...,0.998512,The plenary assembly of the colony passed a ve...

In [83]:
def set_translation_final(df):
    """ONLY creates translation_final column per your spec."""

    df_work = df.copy()
    df_work['oare_id'] = df_work['oare_id'].astype(str)

    def process_group(group):
        if len(group) == 1:
            
            group['translation_final'] = group['translation'].iloc[0]
        else:
            
            group['translation_final'] = group['translation_sent']

            
            if len(group) > 2 and 'similarity_score' in group.columns:
                sim_mean = pd.to_numeric(group['similarity_score'], errors='coerce').mean()
                if not pd.isna(sim_mean) and sim_mean < 0.9:
                    print(f"Low similarity oare_id {group.name}: {sim_mean:.3f}")

        return group

    result = df_work.groupby('oare_id').apply(process_group).reset_index(drop=True)

    print(f"Added translation_final to {len(result)} rows")
    return result


df_final = set_translation_final(result_df_merged)
df_final

⚠️ Low similarity oare_id 004a7dbd-57ce-46f8-9691-409be61c676e: 0.890
⚠️ Low similarity oare_id 03afa072-8f71-4403-b303-086f6097db3f: 0.835
⚠️ Low similarity oare_id 11672d83-b960-4dad-8399-05c077aead07: 0.899
⚠️ Low similarity oare_id 154bfa3c-bd94-439c-b139-06e6d0a027af: 0.896
⚠️ Low similarity oare_id 17eabcc2-84f1-4fb0-b151-af6331cb4d17: 0.869
⚠️ Low similarity oare_id 1f969304-1971-4333-85cc-39a89ef6a900: 0.828
⚠️ Low similarity oare_id 27241e71-4aa3-4a89-9235-991efc5022e6: 0.846
⚠️ Low similarity oare_id 2ee64c13-a638-4006-af31-c4b6b39d077c: 0.755
⚠️ Low similarity oare_id 2fae4254-c181-4378-a0a5-359c85c791a5: 0.827
⚠️ Low similarity oare_id 31f0a2fb-00be-4f3a-b5f5-036afa8582f8: 0.454
⚠️ Low similarity oare_id 3a1e965b-3b71-452c-84a2-7416f7cdf986: 0.714
⚠️ Low similarity oare_id 4633e49c-6469-4b90-a381-a9853f1c0b9f: 0.694
⚠️ Low similarity oare_id 4871d3be-b7b2-4953-8ef1-f227902488da: 0.886
⚠️ Low similarity oare_id 4a1ecde0-c0f0-4170-a0bf-bc8fc0c997a9: 0.668
⚠️ Low similarity oare_id 4aac0b6b-c7eb-4efb-b988-2df596dad287: 0.400
⚠️ Low similarity oare_id 4cce0418-d5ac-4331-9793-a99d9efe2fce: 0.795
⚠️ Low similarity oare_id 4eb23b20-e6ce-4c45-ac07-07d62a2ef0d0: 0.737
⚠️ Low similarity oare_id 4fb0aca8-2ccd-4429-bef1-fe9999ce9b7b: 0.856
⚠️ Low similarity oare_id 52a72ed1-d6fe-4d58-85d4-987937084fc0: 0.479
⚠️ Low similarity oare_id 54364e47-54dc-4022-9c48-9006a2fe1b53: 0.319
⚠️ Low similarity oare_id 624ec652-d489-482b-a557-27a3fa01273e: 0.847
⚠️ Low similarity oare_id 6d6519ac-25a4-4043-a389-616fba75e1d3: 0.856
⚠️ Low similarity oare_id 6e81bb53-74f5-42cc-8e63-26acc396a6cd: 0.797
⚠️ Low similarity oare_id 6fa9e677-2dcc-46a1-8bbf-3b87c4a8f2e2: 0.786
⚠️ Low similarity oare_id 7e5a013d-0e71-43bf-a8ae-ce07c4a701f2: 0.765
⚠️ Low similarity oare_id 803449c3-3581-4dbc-b973-a2a65254b224: 0.853
⚠️ Low similarity oare_id 8154fdaf-852f-4fdb-a932-fdb598e4ac91: 0.850
⚠️ Low similarity oare_id 842f390f-7848-46b8-b9c1-86cadb3ee753: 0.885
⚠️ Low similarity oare_id 9298628f-c336-4602-a716-deb96f7802a7: 0.719
⚠️ Low similarity oare_id 93040e53-ffd8-43ef-a7be-163d7a58fcb4: 0.891
⚠️ Low similarity oare_id 9519f8d6-02cb-4d7d-b71b-9ccef82299e5: 0.857
⚠️ Low similarity oare_id a9836a99-7113-4fab-aace-9363e23415d3: 0.875
⚠️ Low similarity oare_id ae3c9a62-b6cf-4613-b686-d724bb6e0001: 0.877
⚠️ Low similarity oare_id aefa478d-c47d-42d2-a3b5-3f150603ccee: 0.897
⚠️ Low similarity oare_id b1448360-1805-4f54-a1d4-c113cb0d7d58: 0.887
⚠️ Low similarity oare_id bc0c7ffd-4db1-4d83-8a75-d921739077d1: 0.867
⚠️ Low similarity oare_id bc569fa1-ce83-4a7e-9deb-2cb2f83ad027: 0.770
⚠️ Low similarity oare_id bdf62c81-286c-407f-98f4-8674d658779b: 0.726
⚠️ Low similarity oare_id c4f56b6d-4f1f-4d12-808f-5c55cdf2eb1f: 0.775
⚠️ Low similarity oare_id cc813851-7f2c-4f1d-b91f-127d797f411b: 0.174
⚠️ Low similarity oare_id cde3a4b0-6249-49ec-a62b-4fee8d458cb2: 0.870
⚠️ Low similarity oare_id d290a525-1284-44b3-b12f-e222484dcc44: 0.437
⚠️ Low similarity oare_id e20a13b7-d098-4d9f-9675-2eae5c4f9aad: 0.765
⚠️ Low similarity oare_id e7591a56-60ec-429a-9ac0-7826240834db: 0.888
⚠️ Low similarity oare_id ea41bf02-3232-47ae-96ab-06c1a85ff71e: 0.869
⚠️ Low similarity oare_id eadec8f8-48e1-4dc9-a3c5-737481746d17: 0.880
⚠️ Low similarity oare_id f352e4ba-65ff-43bf-88ce-8e3e073943be: 0.806
⚠️ Low similarity oare_id f57b8fce-716d-4d0c-a0ba-bdabaa6584ae: 0.809
⚠️ Low similarity oare_id fca76fd0-dbb1-42f5-a978-fc683270e374: 0.863
⚠️ Low similarity oare_id fd482abc-8de7-4157-88c4-f1a3e80f5a67: 0.704
✅ Added translation_final to 1213 rows

/tmp/ipython-input-1121768001.py:23: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df_work.groupby('oare_id').apply(process_group).reset_index(drop=True)

,oare_id,translation_sent,translation,transliteration,first_word_spelling,first_word_number,first_word_obj_in_text,line_number,side,column,para_to_sentence,similarity_score,translation_sent_flat,translation_final
0,004a7dbd-57ce-46f8-9691-409be61c676e,"Seals of Mannum-bālum-Aššur s. ?, Šū-Enlil s. ...","Seal of Mannum-balum-Aššur son of Ṣilli-Adad, ...",KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-(d)IM KIŠI...,KIŠIB,1,5,1.0,1,1,KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-(d)IM KIŠI...,0.890118,"Seals of Mannum-bālum-Aššur s. ?, Šū-Enlil s. ...","Seals of Mannum-bālum-Aššur s. ?, Šū-Enlil s. ..."
1,004a7dbd-57ce-46f8-9691-409be61c676e,Puzur-Aššur s. Attaya owes Al-aḫum 1/3 mina 2 ...,"Seal of Mannum-balum-Aššur son of Ṣilli-Adad, ...",KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-(d)IM KIŠI...,ma-na,14,31,5.0,1,1,ma-na 2 GÍN KÙ.BABBAR SIG₅ i-ṣé-er PUZUR₄-a-šu...,0.890118,"Seals of Mannum-bālum-Aššur s. ?, Šū-Enlil s. ...",Puzur-Aššur s. Attaya owes Al-aḫum 1/3 mina 2 ...
2,004a7dbd-57ce-46f8-9691-409be61c676e,He will pay fourteen weeks from the ḫamuštum o...,"Seal of Mannum-balum-Aššur son of Ṣilli-Adad, ...",KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-(d)IM KIŠI...,iš-tù,25,50,8.0,1,1,iš-tù ḫa-muš-tim ša ì-lí-dan ITU.KAM ša ke-na-...,0.890118,"Seals of Mannum-bālum-Aššur s. ?, Šū-Enlil s. ...",He will pay fourteen weeks from the ḫamuštum o...
3,004a7dbd-57ce-46f8-9691-409be61c676e,"If he does not pay (on time), he will add 1.5 ...","Seal of Mannum-balum-Aššur son of Ṣilli-Adad, ...",KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-(d)IM KIŠI...,šu-ma,39,73,13.0,1,1,šu-ma lá iš-qú-ul 1.5 GÍN.TA a-na 1 ma-na-im i...,0.890118,"Seals of Mannum-bālum-Aššur s. ?, Šū-Enlil s. ...","If he does not pay (on time), he will add 1.5 ..."
4,009fb838-8038-42bc-ad34-5f795b3840ee,"Seal of Šu-Illil son of Šu-kūbum, seal of Şilū...","Seal of Šu-Illil son of Šu-Kūbum, seal of Ṣilū...",KIŠIB šu-(d)EN.LÍL DUMU šu-ku-bi-im KIŠIB ṣí-l...,KIŠIB,1,4,1.0,1,1,KIŠIB šu-(d)EN.LÍL DUMU šu-ku-bi-im KIŠIB ṣí-l...,0.970273,"Seal of Šu-Illil son of Šu-kūbum, seal of Şilū...","Seal of Šu-Illil son of Šu-kūbum, seal of Şilū..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1208,fded4d2f-81a5-45b3-8d62-74e5ffb2e159,As to the goods belonging to Šalim-Aššur that ...,"Seal of Kula brother of Šukkutum, seal of Puzu...",KIŠIB ku-la a-ḫu-ú šu-ku-tim KIŠIB PUZUR₄-tí-a...,lu-qú-tám,20,36,5.0,1,1,lu-qú-tám ša ša-lim-a-šur ša i-na ḫa-ḫi-im É i...,0.988610,"Seal of Kula brother of Šukkutum, seal of Puzu...",As to the goods belonging to Šalim-Aššur that ...
1209,fe0b8448-f09e-47cf-b1e8-8e8d96531bb3,"To Adida, Al-aḫum and Uku from Puzur-Aššur","To Adida, Ali-ahum, and Uku from Puzur-Aššur: ...",a-na a-dí-da a-la-ḫi-im ú ú-ku-ú qí-bi₄-ma um-...,a-na,1,5,1.0,1,1,a-na a-dí-da a-la-ḫi-im ú ú-ku-ú qí-bi₄-ma um-...,0.523545,"To Adida, Al-aḫum and Uku from Puzur-Aššur To ...","To Adida, Al-aḫum and Uku from Puzur-Aššur"
1210,fe0b8448-f09e-47cf-b1e8-8e8d96531bb3,To Uku from Puzur-Aššur:,"To Adida, Ali-ahum, and Uku from Puzur-Aššur: ...",a-na a-dí-da a-la-ḫi-im ú ú-ku-ú qí-bi₄-ma um-...,a-na,32,48,11.0,1,1,a-na ú-ku-ú qí-bi₄-ma um-ma PUZUR₄-a-šur-ma la...,0.523545,"To Adida, Al-aḫum and Uku from Puzur-Aššur To ...",To Uku from Puzur-Aššur:
1211,ff43a284-3d67-4238-8b4a-9b6cb7531e0a,Ilī-ašrannī son of Sukkalliya has received 3 m...,Ilī-ašrannī son of Sukkalliya has received 3 m...,3 ma-na KÙ.BABBAR ṣa-ru-pá-am i-na ší-im SÍG.Ḫ...,ma-na,2,6,1.0,1,1,ma-na KÙ.BABBAR ṣa-ru-pá-am i-na ší-im SÍG.ḪI....,1.000000,Ilī-ašrannī son of Sukkalliya has received 3 m...,Ilī-ašrannī son of Sukkalliya has received 3 m...
1212,ff43a284-3d67-4238-8b4a-9b6cb7531e0a,"Witnessed by Aššur-bāni son of Kurbiya, by Išm...",Ilī-ašrannī son of Sukkalliya has received 3 m...,3 ma-na KÙ.BABBAR ṣa-ru-pá-am i-na ší-im SÍG.Ḫ...,IGI,14,23,8.0,2,1,IGI a-šùr-ba-ni DUMU kur-bi-a-a IGI iš-me-DING...,1.000000,Ilī-ašrannī son of Sukkalliya has received 3 m...,"Witnessed by Aššur-bāni son of Kurbiya, by Išm..."

In [84]:
df_final

,oare_id,translation_sent,translation,transliteration,first_word_spelling,first_word_number,first_word_obj_in_text,line_number,side,column,para_to_sentence,similarity_score,translation_sent_flat,translation_final
0,004a7dbd-57ce-46f8-9691-409be61c676e,"Seals of Mannum-bālum-Aššur s. ?, Šū-Enlil s. ...","Seal of Mannum-balum-Aššur son of Ṣilli-Adad, ...",KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-(d)IM KIŠI...,KIŠIB,1,5,1.0,1,1,KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-(d)IM KIŠI...,0.890118,"Seals of Mannum-bālum-Aššur s. ?, Šū-Enlil s. ...","Seals of Mannum-bālum-Aššur s. ?, Šū-Enlil s. ..."
1,004a7dbd-57ce-46f8-9691-409be61c676e,Puzur-Aššur s. Attaya owes Al-aḫum 1/3 mina 2 ...,"Seal of Mannum-balum-Aššur son of Ṣilli-Adad, ...",KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-(d)IM KIŠI...,ma-na,14,31,5.0,1,1,ma-na 2 GÍN KÙ.BABBAR SIG₅ i-ṣé-er PUZUR₄-a-šu...,0.890118,"Seals of Mannum-bālum-Aššur s. ?, Šū-Enlil s. ...",Puzur-Aššur s. Attaya owes Al-aḫum 1/3 mina 2 ...
2,004a7dbd-57ce-46f8-9691-409be61c676e,He will pay fourteen weeks from the ḫamuštum o...,"Seal of Mannum-balum-Aššur son of Ṣilli-Adad, ...",KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-(d)IM KIŠI...,iš-tù,25,50,8.0,1,1,iš-tù ḫa-muš-tim ša ì-lí-dan ITU.KAM ša ke-na-...,0.890118,"Seals of Mannum-bālum-Aššur s. ?, Šū-Enlil s. ...",He will pay fourteen weeks from the ḫamuštum o...
3,004a7dbd-57ce-46f8-9691-409be61c676e,"If he does not pay (on time), he will add 1.5 ...","Seal of Mannum-balum-Aššur son of Ṣilli-Adad, ...",KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-(d)IM KIŠI...,šu-ma,39,73,13.0,1,1,šu-ma lá iš-qú-ul 1.5 GÍN.TA a-na 1 ma-na-im i...,0.890118,"Seals of Mannum-bālum-Aššur s. ?, Šū-Enlil s. ...","If he does not pay (on time), he will add 1.5 ..."
4,009fb838-8038-42bc-ad34-5f795b3840ee,"Seal of Šu-Illil son of Šu-kūbum, seal of Şilū...","Seal of Šu-Illil son of Šu-Kūbum, seal of Ṣilū...",KIŠIB šu-(d)EN.LÍL DUMU šu-ku-bi-im KIŠIB ṣí-l...,KIŠIB,1,4,1.0,1,1,KIŠIB šu-(d)EN.LÍL DUMU šu-ku-bi-im KIŠIB ṣí-l...,0.970273,"Seal of Šu-Illil son of Šu-kūbum, seal of Şilū...","Seal of Šu-Illil son of Šu-kūbum, seal of Şilū..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1208,fded4d2f-81a5-45b3-8d62-74e5ffb2e159,As to the goods belonging to Šalim-Aššur that ...,"Seal of Kula brother of Šukkutum, seal of Puzu...",KIŠIB ku-la a-ḫu-ú šu-ku-tim KIŠIB PUZUR₄-tí-a...,lu-qú-tám,20,36,5.0,1,1,lu-qú-tám ša ša-lim-a-šur ša i-na ḫa-ḫi-im É i...,0.988610,"Seal of Kula brother of Šukkutum, seal of Puzu...",As to the goods belonging to Šalim-Aššur that ...
1209,fe0b8448-f09e-47cf-b1e8-8e8d96531bb3,"To Adida, Al-aḫum and Uku from Puzur-Aššur","To Adida, Ali-ahum, and Uku from Puzur-Aššur: ...",a-na a-dí-da a-la-ḫi-im ú ú-ku-ú qí-bi₄-ma um-...,a-na,1,5,1.0,1,1,a-na a-dí-da a-la-ḫi-im ú ú-ku-ú qí-bi₄-ma um-...,0.523545,"To Adida, Al-aḫum and Uku from Puzur-Aššur To ...","To Adida, Al-aḫum and Uku from Puzur-Aššur"
1210,fe0b8448-f09e-47cf-b1e8-8e8d96531bb3,To Uku from Puzur-Aššur:,"To Adida, Ali-ahum, and Uku from Puzur-Aššur: ...",a-na a-dí-da a-la-ḫi-im ú ú-ku-ú qí-bi₄-ma um-...,a-na,32,48,11.0,1,1,a-na ú-ku-ú qí-bi₄-ma um-ma PUZUR₄-a-šur-ma la...,0.523545,"To Adida, Al-aḫum and Uku from Puzur-Aššur To ...",To Uku from Puzur-Aššur:
1211,ff43a284-3d67-4238-8b4a-9b6cb7531e0a,Ilī-ašrannī son of Sukkalliya has received 3 m...,Ilī-ašrannī son of Sukkalliya has received 3 m...,3 ma-na KÙ.BABBAR ṣa-ru-pá-am i-na ší-im SÍG.Ḫ...,ma-na,2,6,1.0,1,1,ma-na KÙ.BABBAR ṣa-ru-pá-am i-na ší-im SÍG.ḪI....,1.000000,Ilī-ašrannī son of Sukkalliya has received 3 m...,Ilī-ašrannī son of Sukkalliya has received 3 m...
1212,ff43a284-3d67-4238-8b4a-9b6cb7531e0a,"Witnessed by Aššur-bāni son of Kurbiya, by Išm...",Ilī-ašrannī son of Sukkalliya has received 3 m...,3 ma-na KÙ.BABBAR ṣa-ru-pá-am i-na ší-im SÍG.Ḫ...,IGI,14,23,8.0,2,1,IGI a-šùr-ba-ni DUMU kur-bi-a-a IGI iš-me-DING...,1.000000,Ilī-ašrannī son of Sukkalliya has received 3 m...,"Witnessed by Aššur-bāni son of Kurbiya, by Išm..."

In [111]:
shashank_df = df_final[['oare_id', 'para_to_sentence', 'translation_final']]
shashank_df

,oare_id,para_to_sentence,translation_final
0,004a7dbd-57ce-46f8-9691-409be61c676e,KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-(d)IM KIŠI...,"Seals of Mannum-bālum-Aššur s. ?, Šū-Enlil s. ..."
1,004a7dbd-57ce-46f8-9691-409be61c676e,ma-na 2 GÍN KÙ.BABBAR SIG₅ i-ṣé-er PUZUR₄-a-šu...,Puzur-Aššur s. Attaya owes Al-aḫum 1/3 mina 2 ...
2,004a7dbd-57ce-46f8-9691-409be61c676e,iš-tù ḫa-muš-tim ša ì-lí-dan ITU.KAM ša ke-na-...,He will pay fourteen weeks from the ḫamuštum o...
3,004a7dbd-57ce-46f8-9691-409be61c676e,šu-ma lá iš-qú-ul 1.5 GÍN.TA a-na 1 ma-na-im i...,"If he does not pay (on time), he will add 1.5 ..."
4,009fb838-8038-42bc-ad34-5f795b3840ee,KIŠIB šu-(d)EN.LÍL DUMU šu-ku-bi-im KIŠIB ṣí-l...,"Seal of Šu-Illil son of Šu-kūbum, seal of Şilū..."
...,...,...,...
1208,fded4d2f-81a5-45b3-8d62-74e5ffb2e159,lu-qú-tám ša ša-lim-a-šur ša i-na ḫa-ḫi-im É i...,As to the goods belonging to Šalim-Aššur that ...
1209,fe0b8448-f09e-47cf-b1e8-8e8d96531bb3,a-na a-dí-da a-la-ḫi-im ú ú-ku-ú qí-bi₄-ma um-...,"To Adida, Al-aḫum and Uku from Puzur-Aššur"
1210,fe0b8448-f09e-47cf-b1e8-8e8d96531bb3,a-na ú-ku-ú qí-bi₄-ma um-ma PUZUR₄-a-šur-ma la...,To Uku from Puzur-Aššur:
1211,ff43a284-3d67-4238-8b4a-9b6cb7531e0a,ma-na KÙ.BABBAR ṣa-ru-pá-am i-na ší-im SÍG.ḪI....,Ilī-ašrannī son of Sukkalliya has received 3 m...
1212,ff43a284-3d67-4238-8b4a-9b6cb7531e0a,IGI a-šùr-ba-ni DUMU kur-bi-a-a IGI iš-me-DING...,"Witnessed by Aššur-bāni son of Kurbiya, by Išm..."

In [112]:
shashank_df = shashank_df.rename(columns={'para_to_sentence': 'transliteration'})
shashank_df

,oare_id,transliteration,translation_final
0,004a7dbd-57ce-46f8-9691-409be61c676e,KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-(d)IM KIŠI...,"Seals of Mannum-bālum-Aššur s. ?, Šū-Enlil s. ..."
1,004a7dbd-57ce-46f8-9691-409be61c676e,ma-na 2 GÍN KÙ.BABBAR SIG₅ i-ṣé-er PUZUR₄-a-šu...,Puzur-Aššur s. Attaya owes Al-aḫum 1/3 mina 2 ...
2,004a7dbd-57ce-46f8-9691-409be61c676e,iš-tù ḫa-muš-tim ša ì-lí-dan ITU.KAM ša ke-na-...,He will pay fourteen weeks from the ḫamuštum o...
3,004a7dbd-57ce-46f8-9691-409be61c676e,šu-ma lá iš-qú-ul 1.5 GÍN.TA a-na 1 ma-na-im i...,"If he does not pay (on time), he will add 1.5 ..."
4,009fb838-8038-42bc-ad34-5f795b3840ee,KIŠIB šu-(d)EN.LÍL DUMU šu-ku-bi-im KIŠIB ṣí-l...,"Seal of Šu-Illil son of Šu-kūbum, seal of Şilū..."
...,...,...,...
1208,fded4d2f-81a5-45b3-8d62-74e5ffb2e159,lu-qú-tám ša ša-lim-a-šur ša i-na ḫa-ḫi-im É i...,As to the goods belonging to Šalim-Aššur that ...
1209,fe0b8448-f09e-47cf-b1e8-8e8d96531bb3,a-na a-dí-da a-la-ḫi-im ú ú-ku-ú qí-bi₄-ma um-...,"To Adida, Al-aḫum and Uku from Puzur-Aššur"
1210,fe0b8448-f09e-47cf-b1e8-8e8d96531bb3,a-na ú-ku-ú qí-bi₄-ma um-ma PUZUR₄-a-šur-ma la...,To Uku from Puzur-Aššur:
1211,ff43a284-3d67-4238-8b4a-9b6cb7531e0a,ma-na KÙ.BABBAR ṣa-ru-pá-am i-na ší-im SÍG.ḪI....,Ilī-ašrannī son of Sukkalliya has received 3 m...
1212,ff43a284-3d67-4238-8b4a-9b6cb7531e0a,IGI a-šùr-ba-ni DUMU kur-bi-a-a IGI iš-me-DING...,"Witnessed by Aššur-bāni son of Kurbiya, by Išm..."

In [113]:
shashank_df = shashank_df.rename(columns={'translation_final': 'translation'})

In [114]:
shashank_df

,oare_id,transliteration,translation
0,004a7dbd-57ce-46f8-9691-409be61c676e,KIŠIB ma-nu-ba-lúm-a-šur DUMU ṣí-lá-(d)IM KIŠI...,"Seals of Mannum-bālum-Aššur s. ?, Šū-Enlil s. ..."
1,004a7dbd-57ce-46f8-9691-409be61c676e,ma-na 2 GÍN KÙ.BABBAR SIG₅ i-ṣé-er PUZUR₄-a-šu...,Puzur-Aššur s. Attaya owes Al-aḫum 1/3 mina 2 ...
2,004a7dbd-57ce-46f8-9691-409be61c676e,iš-tù ḫa-muš-tim ša ì-lí-dan ITU.KAM ša ke-na-...,He will pay fourteen weeks from the ḫamuštum o...
3,004a7dbd-57ce-46f8-9691-409be61c676e,šu-ma lá iš-qú-ul 1.5 GÍN.TA a-na 1 ma-na-im i...,"If he does not pay (on time), he will add 1.5 ..."
4,009fb838-8038-42bc-ad34-5f795b3840ee,KIŠIB šu-(d)EN.LÍL DUMU šu-ku-bi-im KIŠIB ṣí-l...,"Seal of Šu-Illil son of Šu-kūbum, seal of Şilū..."
...,...,...,...
1208,fded4d2f-81a5-45b3-8d62-74e5ffb2e159,lu-qú-tám ša ša-lim-a-šur ša i-na ḫa-ḫi-im É i...,As to the goods belonging to Šalim-Aššur that ...
1209,fe0b8448-f09e-47cf-b1e8-8e8d96531bb3,a-na a-dí-da a-la-ḫi-im ú ú-ku-ú qí-bi₄-ma um-...,"To Adida, Al-aḫum and Uku from Puzur-Aššur"
1210,fe0b8448-f09e-47cf-b1e8-8e8d96531bb3,a-na ú-ku-ú qí-bi₄-ma um-ma PUZUR₄-a-šur-ma la...,To Uku from Puzur-Aššur:
1211,ff43a284-3d67-4238-8b4a-9b6cb7531e0a,ma-na KÙ.BABBAR ṣa-ru-pá-am i-na ší-im SÍG.ḪI....,Ilī-ašrannī son of Sukkalliya has received 3 m...
1212,ff43a284-3d67-4238-8b4a-9b6cb7531e0a,IGI a-šùr-ba-ni DUMU kur-bi-a-a IGI iš-me-DING...,"Witnessed by Aššur-bāni son of Kurbiya, by Išm..."

In [116]:
shashank_df['translation'][400]

'Because of these matters which Alpilī told her, when I had arrived for five days she refused to talk with me.'

In [103]:
shashank_df.to_csv('shashank_df.csv')

In [104]:
files.download('shashank_df.csv')